/**
 * Created by raz on 4/2/14.
 */
public enum FieldDirection {
    START_LOCATION,
    WATER_WELL,
    SALINITY_DISPENSER_BOTTOM,
    SALINITY_DISPENSER_TOP,
     TURBIDITY_DISPENSER_BOTTOM,
    TURBIDITY_DISPENSER_TOP,
    BEFORE_CROSS_BRIDGE_LEFT,
    AFTER_CROSS_BRIDGE,
    DROP_OFF_LOCATION,

}
